master:
  merge_request:
    # Python的CI检查
    - docker:
        image: python:3.12-slim # 通过此参数控制使用的镜像环境
      stages:
        - name: Start Python CI
          script:
            - echo "Python unit test started"
        - name: Install uv
          script:
            - pip install -i https://mirrors.tencent.com/pypi/simple/ uv
            - uv sync
        - name: Code Style Test
          script:
            - uv run pre-commit run --all-files
        - name: Unit tests
          script:
            - uv run python -m unittest discover -s tests -p "test_[!a]*.py"
